default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: <%= ENV.fetch("DB_USERNAME", "postgres") %>
  password: <%= ENV.fetch("DB_PASSWORD", "") %>
  pool: 5

development:
  <<: *default
  database: shortener_development

test:
  <<: *default
  database: shortener_test

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
